FROM node:8-stretch

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN apt-get update && apt-get install git
COPY package.json /usr/src/app/
RUN npm install --registry=https://registry.npm.taobao.org

COPY . /usr/src/app
RUN npm run build
ENTRYPOINT ["node", "index.js"]
